---
- name: create destination dir for generated readme
  file:
    path: "output/"
    state: directory

- name: write docker-compose file
  template:
    src: ../templates/docker-compose.yml.j2
    dest: "output/docker-compose.yml"
  delegate_to: localhost